name: tcpdump-test1
version: 0.2
summary: Testing Permissions
description:
  Testing raw packet access
confinement: devmode
grade: devel


parts:
  tcpdump:
    plugin: dump
    source: .
    build-packages: [libpcap-dev]
    stage-packages: [libpcap0.8]
    stage:
      - libpcap.so.1
      - tcpdump
    

apps:
  tcpdump-test1:
    command: ./tcpdump
    plugs: [network, network-bind, raw-usb]
