name: tcpdump1
version: 4
summary: Testing Permissions
description:
  Testing raw packet access
confinement: devmode
grade: devel


parts:
  tcpdump1:
    plugin: dump
    source: .
    build-packages: [libpcap-dev]
    stage-packages: [libpcap0.8]
    stage:
      - tcpdump
      - libpcap.so.1
      - usr/lib
      - usr/share
    
    

apps:
  tcpdump1:
    command: ./tcpdump
    plugs: [network, network-bind, raw-usb]
